require "__shared/Items/Definitions/BRItemDefinition"
require "__shared/Enums/ItemEnums"

local m_WeaponDefinitions = require "__shared/Items/Definitions/BRItemWeaponDefinition"

class("BRItemAttachmentDefinition", BRItemDefinition)

function BRItemAttachmentDefinition:__init(
    p_UId,
    p_Name,
    p_Description,
    p_Weight,
    p_UIIcon,
    p_Mesh,
    p_CompatibleWith,
    p_AttachmentType,
    p_AttachmentId
)
    BRItemDefinition.__init(self)

    self.m_Type = ItemType.Attachment
    self.m_UId = p_UId
    self.m_Name = p_Name
    self.m_Description = p_Description
    self.m_Weight = p_Weight
    self.m_Mesh = p_Mesh
    self.m_UIIcon = p_UIIcon
    self.m_Stackable = false
    self.m_MaxStack = nil
    self.m_Price = 0
    
    -- A list of weapon definitions from BRItemWeaponDefinition
    self.m_CompatibleWith = p_CompatibleWith
    self.m_AttachmentType = p_AttachmentType
    self.m_AttachmentId = p_AttachmentId -- TODO: Rename this lol
end

return {
    -- Optics
    ["attachment-acog"] = BRItemAttachmentDefinition(
        "attachment-acog",
        "4x ACOG", 
        "The ACOG scope allows for the user to engage targets at medium to long ranges.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/acog",
        DC(Guid("D01B86C8-5176-E446-85CB-DE8871DAC528"), Guid("D7875B6B-37F1-4C5D-60CD-273DDA3E553F")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Optics,
        g_AttachmentIds.Acog
    ),
    ["attachment-kobra"] = BRItemAttachmentDefinition(
        "attachment-kobra",
        "Kobra", 
        "The Kobra is a Russian Red Dot Sight used by military and police organizations on AK style mounts, with some variants adapted to fit standard accessory rails.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/kobra",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Optics,
        g_AttachmentIds.Kobra
    ),
    ["attachment-holo"] = BRItemAttachmentDefinition(
        "attachment-holo",
        "Holographic Sight", 
        "A Holographic Weapon Sight is a non-magnifying gun sight that allows the user to look through a glass optical window and see a cross hair reticle image superimposed at a distance on the field of view.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/eotech",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Optics,
        g_AttachmentIds.EOTech
    ),
    ["attachment-pka"] = BRItemAttachmentDefinition(
        "attachment-pka",
        "PK-A", 
        "The PK-A red dot sight is a reflex sight produced by BelOMO in Minsk, Belarus.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/pka",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Optics,
        g_AttachmentIds.PKA
    ),
    ["attachment-pka-s"] = BRItemAttachmentDefinition(
        "attachment-pka-s",
        "PKA-S", 
        "The PK-AS/ASV is an advanced reflex sight manufactured by BelOMO (Belarusian Optical & Mechanical Association).",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/pkas",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Optics,
        g_AttachmentIds.PK_AS
    ),
    ["attachment-riflescope"] = BRItemAttachmentDefinition(
        "attachment-riflescope",
        "Rifle Scope", 
        "The Rifle Scope is a weapon optic available on assault rifles, carbines, shotguns, magazine-fed LMGs, the AS VAL and the Sniper rifles.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/riflescope",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
        },
        AttachmentType.Optics,
        g_AttachmentIds.RifleScope
    ),

    -- Barrels (Primary)
    ["attachment-suppressor"] = BRItemAttachmentDefinition(
        "attachment-suppressor",
        "Suppressor", 
        "The Suppressor is a device attached to a firearm which reduces the amount of noise generated by firing the weapon.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/soundsuppressor",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Barrel,
        g_AttachmentIds.Silencer
    ),
    ["attachment-flash-suppressor"] = BRItemAttachmentDefinition(
        "attachment-flash-suppressor",
        "Flash Hider", 
        "A flash suppressor, also known as a flash hider is a device attached to the muzzle of a rifle or other firearm that reduces the visible signature of the burning gases that exit the muzzle, which may also reduce recoil.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/flashsuppressor",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Barrel,
        g_AttachmentIds.FlashSuppressor
    ),
    ["attachment-heavy-barrel"] = BRItemAttachmentDefinition(
        "attachment-heavy-barrel",
        "Heavy Barrel", 
        "A Heavy Barrel is a weapon attachment used to increase a weapon's accuracy by reducing barrel whip.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/heavybarrel",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Barrel,
        g_AttachmentIds.HeavyBarrel
    ),
    ["attachment-flashlight"] = BRItemAttachmentDefinition(
        "attachment-flashlight",
        "Tactical Light", 
        "A Tactical Light is a flashlight or torch that can be attached to a user's weapon by means of a standard rail or other mount, freeing the user from having to carry a separate flashlight, or when more advanced night vision equipment is not available.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/flashlight",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Barrel,
        g_AttachmentIds.Flashlight
    ),

    -- Other (Secondary)
    ["attachment-foregrip"] = BRItemAttachmentDefinition(
        "attachment-foregrip",
        "Foregrip", 
        "A Foregrip is a grip on the front of a firearm that makes controlling recoil easier, and prevents burns from the barrel during firing.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/foregrip",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
        },
        AttachmentType.Other,
        g_AttachmentIds.Foregrip
    ),
    ["attachment-laser-sight"] = BRItemAttachmentDefinition(
        "attachment-laser-sight",
        "Laser Sight", 
        "The laser has in most firearms applications been used as a tool to enhance the targeting of other weapon systems. ",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/targetpointer",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")), -- TODO FIXME
        {
            m_WeaponDefinitions["weapon-ak74m"],
            m_WeaponDefinitions["weapon-pp2000"],
        },
        AttachmentType.Other,
        g_AttachmentIds.TargetPointer
    ),
    
    
}
