require "__shared/Items/Definitions/BRItemDefinition"
require "__shared/Enums/ItemEnums"

local m_WeaponDefinitions = require "__shared/Items/Definitions/BRItemWeaponDefinition"

class("BRItemAttachmentDefinition", BRItemDefinition)

function BRItemAttachmentDefinition:__init(
    p_Name, 
    p_Description,
    p_Weight,
    p_UIIcon,
    p_Mesh,
    p_CompatibleWith,
    p_AttachmentType
)
    BRItemDefinition.__init(self)

    self.m_Type = ItemType.Attachment
    self.m_Name = p_Name
    self.m_Description = p_Description
    self.m_Weight = p_Weight
    self.m_Mesh = p_Mesh
    self.m_UIIcon = p_UIIcon
    self.m_Stackable = false
    self.m_MaxStack = nil
    self.m_Price = 0
    
    -- A list of weapon definitions from BRItemWeaponDefinition
    self.m_CompatibleWith = p_CompatibleWith
    self.m_AttachmentType = p_AttachmentType
end

return {
    ACOG = BRItemAttachmentDefinition(
        "4x ACOG", 
        "The ACOG scope allows for the user to engage targets at medium to long ranges.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/acog",
        DC(Guid("D01B86C8-5176-E446-85CB-DE8871DAC528"), Guid("D7875B6B-37F1-4C5D-60CD-273DDA3E553F")),
        {
            m_WeaponDefinitions["AK-74M"],
            m_WeaponDefinitions["PP-2000"]
        },
        AttachmentType.Optics
    ),
    Suppressor = BRItemAttachmentDefinition(
        "Suppressor", 
        "The Suppressor is a device attached to a firearm which reduces the amount of noise generated by firing the weapon.",
        25,
        "UI/Art/Persistence/WeaponAccessory/Fancy/soundsuppressor",
        DC(Guid("0B08EAEF-553D-CAD3-D7A4-CA770735FFFA"), Guid("F8FC2931-D0E1-3102-5FD0-E474B9CAAB66")),
        {
            m_WeaponDefinitions["AK-74M"],
            m_WeaponDefinitions["PP-2000"]
        },
        AttachmentType.Barrel
    ),
}
